john-dw/RentMyBike

- app/assets/stylesheets/components/_card-bike.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Please review the app footer which includes:
- social media links (blank links)
- copyright
- sign-in/sign-up links
- Thanks
> created footer

- app/models/user.rb
- app/views/shared/_navbar.html.erb
Please review the first version of the navbar. Some links will need to be updated when the corresponding views have been created.
Some validations for the user model have been added too.
> navbar modified and validations on user model

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Please review this simple banner on the homepage with button redirect to bike index.
> banner on the homepage

- app/models/bike.rb
- app/views/bikes/_form.html.erb
- app/views/bikes/new.html.erb
Adding a dropdown menu to the category input in bike's form
Refacto Bike's form in a partial and call a render in Bike's new view
> Adding Category dropdown to Bike Model and creating partial for the form

- app/controllers/bikes_controller.rb
- app/views/bikes/edit.html.erb
Hello team,
I've been working on the bike update:
- added edit method to bikes controller
- added update method to bikes controller
- created edit views in bikes folder
Happy pulling! :-)
> Added edit and update methods to bike controller + edit view

- app/views/bikes/edit.html.erb
Hello,
just updated the bike>edit view in order to link to _form partial
:-)
> Updated render link to partial _form

- app/controllers/bikes_controller.rb
Added destroy method to Bikes Controller
> Add Delete Method to Bikes Controller

- app/views/bikes/index.html.erb
- app/views/bikes/show.html.erb
Adding a btn in the Bike's show to delete
correcting the link with turbo-method
> Adding BTN delete to Bike show

- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Please review the creation of the dashboard page and route. I made a little modification to the footer for user signed in / sign up logic. Need more styling.
> dashboard page and footer modification

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/bikes/edit.html.erb
- app/views/bikes/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
Adding avatar input to User create and update form
Adding :photo to user parameters in ApplicationController
Adding dependencies to user.rb
> Adding avatar to user form

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
Dashboard tabs layout first draft and footer links modified
> modified footer and started dashboard layout

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card-bike.scss
- app/assets/stylesheets/components/_cards-grid.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/bikes/_cards-grid.erb
- app/views/pages/home.html.erb
Created cards grid
- added html in a partial "card-grid", under bikes views
- created two SCSS components: cards-bike and cards-grid
Each card includes:
- picture uploaded by user
- model
- location
- price per day
- the avatar is not yet dynamic (pending push from JN)
Thanks!
> Cards grid

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/reviews/create.html.erb
- app/views/reviews/destroy.html.erb
- app/views/reviews/new.html.erb
- app/views/reviews/show.html.erb
- config/routes.rb
- test/controllers/reviews_controller_test.rb
hello,
completed Review controller, meaning:
- new, create and destroy methods to review controller
- view "new" from reviews
happy pulling!
> Add reviews controller

- db/migrate/20220823141344_remove_avatar_url_from_users.rb
- db/migrate/20220823141740_remove_picture_url_from_bikes.rb
- db/schema.rb
Deleting avatar_url column in Users table
Deleting picture_url column in Bikes table
> Delete avatar url and picture url from db

- app/controllers/bookings_controller.rb
- db/migrate/20220823142536_add_total_price_to_bookings.rb
- db/schema.rb
Please review the total_price column in bookings and price calculation logic.
> total_price column in bookings and total_price computing in controller

- app/assets/stylesheets/components/_avatar.scss
- app/views/bikes/_cards-grid.erb
card now displays avatar from the user posting the bike offer
> added dynamic avatar

- app/controllers/application_controller.rb
- app/controllers/bikes_controller.rb
- app/views/bikes/show.html.erb
- app/views/reviews/_show.html.erb
- app/views/reviews/show.html.erb
Bike creation fixed
Review show form as a partial, rendering the partial in the bikes show, Work in progress
> Fixing Bike creation and creating partial for Review show

- db/seeds.rb
Modified the seed data to have bikes with coherent data.
> seed with coherent data

- db/seeds.rb
destroy all users and bikes when seed
> destroy all users and bikes when seed

- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- config/routes.rb
- db/seeds.rb
Please review the new dashboard with status changes and added feature of accepting/rejecting requests
> accept bookings logic and frontend

- app/controllers/pages_controller.rb
Remove status change to 'passed' for passed bookings
> change status dashboard controller

- app/views/bikes/_bike_card.html.erb
Hello,
Just added back the avatar to the bike cards
happy pulling!
> Added the line code to have the avatar displayed on each card

- app/assets/stylesheets/components/_card-bike.scss
- app/views/bikes/_bike_card.html.erb
- app/views/bikes/_info_window.html.erb
Hey,
Just adapted the view size in the map display
happy pulling
> Adjust bike card size in map

- app/javascript/controllers/map_controller.js
Hey,
Just added the search fonction, up right on the map of the index view
happy pulling
> Search function working

- app/assets/stylesheets/components/_buton.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Hey,
I did following changes on the navbar:
- centered CTA
- updated dashboard buton
happy pulling
> Adjust navbar design

- app/javascript/controllers/address_autocomplete_controller.js
- app/views/bikes/_form.html.erb
Correcting autocomplete targets to fit location
> Correcting autocomplete

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card-bike.scss
- app/assets/stylesheets/components/_cards-grid.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/bikes/_bike_card.html.erb
- app/views/bikes/index.html.erb
- app/views/layouts/application.html.erb
hey,
I just added font awesome to the bike card for location and fixed minor frontend issues
happy pulling
> Add font awesome icons

- config/environments/production.rb
Updated config file for heroku issue fix
> Updated config>environment>prod

- app/models/bike.rb
- app/models/booking.rb
- db/seeds.rb
Update destroy dependencies on models (To avoid issues on heroku db:seed)
> Updated destroys

- app/models/bike.rb
- app/models/booking.rb
- app/models/review.rb
updated dependent destroys on has_many according to Paul suggestion
> Updated dependent destroys

- app/views/bikes/_form.html.erb
quickfix autocomplete on the add_new_bike view
> Search works

- app/assets/stylesheets/pages/_show.scss
- app/views/bikes/show.html.erb
- app/views/reviews/_new.html.erb
- added reviews to show page
- added back button
- changed format of booking button
> added reviews to show

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/dashboard.html.erb
- app/views/reviews/_new.html.erb
Please see the new dashboard with reviews added and styling changed
> enhanced dashboard

- app/controllers/bikes_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/bikes/show.html.erb
Hello,
I've fixed the marker issues we had with mapbox, meaning:
- marker size
- marker not displayed on the show
happy pulling
> Markers now working

- app/views/reviews/_new.html.erb
- db/seeds.rb
Creating Reviews and booking in seed
> Updating seed

- db/seeds.rb
> Updating IDs in DB Seed

- app/javascript/controllers/compute_price_controller.js
- app/views/bikes/show.html.erb
added "total price" in booking form
fixed code mistake with reviews: added condition of presence of reviews to display reviews
> changed total price and fixed error with reviews

- db/seeds.rb
> correcting seed

- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/dashboard.html.erb
PLease check the new edit button for my bikes in dashboard
> edit button dashboard and button navbar centered

- app/views/bikes/show.html.erb
updated the show by removing model term in the view
> removed Model

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
> changed footer
